[package]
name = "json-utils"
version = "0.2.6"
authors = ["Roman Gafiyatullin <r.gafiyatullin@me.com>"]
edition = "2018"

[dependencies]
failure = "^0.1"
serde_json = "^1.0"
maplit = "^1.0"
valico = "^3.0"

[dependencies.serde]
version = "^1.0"
features = ["derive"]
